import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // generated from openapi.json by `npm run api:types`
    "src/lib/api/schema.d.ts",
    // generated by scripts/build-map-provider.mjs (minified bundle)
    "public/map/**",
    "public/pdfjs/**",
  ]),
]);

export default eslintConfig;
