#!/usr/bin/env bash
# Generates, once, the secrets deploy/.env must carry and never replaces a value already there:
#   bash /opt/urbanview/deploy/ensure-secrets.sh
# deploy.sh runs it after every pull, server-setup.sh when deploy/.env exists. Today one secret:
# SECRETS_ENCRYPTION_KEY, the Fernet key (32 random bytes, url-safe base64) that encrypts what the
# admin console saves (the Anthropic API key: core.app_secrets). A missing or empty line gets a new
# key; a line with a value is left alone, so a second run changes nothing. The key is never printed
# and never passed on a command line. Keep a copy off the server: a restored database cannot
# decrypt the saved secrets without it, and a changed key makes them unreadable.
set -euo pipefail
cd "$(dirname "$0")/.."

env_file=deploy/.env
name=SECRETS_ENCRYPTION_KEY

if [[ ! -f $env_file ]]; then
  echo "deploy/.env is missing: copy deploy/.env.example first" >&2
  exit 1
fi

# A value = anything after the equals sign but blanks, empty quotes or a comment.
if grep -qE "^[[:space:]]*${name}[[:space:]]*=[[:space:]]*[\"']?[^[:space:]#\"']" "$env_file"; then
  exit 0
fi

key="$(openssl rand -base64 32 | tr '+/' '-_')"
if [[ ! $key =~ ^[A-Za-z0-9_-]{43}=$ ]]; then
  echo "could not generate ${name} (openssl rand -base64 32)" >&2
  exit 1
fi

if grep -qE "^[[:space:]]*${name}[[:space:]]*=" "$env_file"; then
  # Fill the empty line in place (the key reaches awk through its environment, not its arguments).
  tmp="$(mktemp "${env_file}.XXXXXX")"
  trap 'rm -f "$tmp"' EXIT
  NEW_SECRET="$key" awk -v name="$name" '
    $0 ~ ("^[ \t]*" name "[ \t]*=") { print name "=" ENVIRON["NEW_SECRET"]; next }
    { print }
  ' "$env_file" > "$tmp"
  mv "$tmp" "$env_file"
  trap - EXIT
else
  printf '\n# generated by deploy/ensure-secrets.sh on %s: encrypts secrets saved in the admin console.\n# Keep a copy off the server: without it a restored database cannot decrypt them.\n%s=%s\n' \
    "$(date -u +%F)" "$name" "$key" >> "$env_file"
fi
chmod 600 "$env_file"
echo "${name} generated in deploy/.env: keep a copy off the server"
